import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import {
  Avatar,
  Box,
  Container,
  Image,
  Text,
} from "@chakra-ui/react";
import { Suspense } from "react";
import { FacebookPixelEvents } from "./pixel-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Glexis A Rodriguez",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Box backgroundColor={"gray.100"} minH={"100vh"}>
            <Box maxH={200} backgroundColor={"green.200"} overflow={"hidden"} >
              <Image src="/cover.jpeg" alt="Cover Glexis" width={"100%"} />
            </Box>
            <Box display="flex" justifyContent="center" marginBottom={4}>
              <Box marginTop={-20}>
                <Avatar
                  size="2xl"
                  name="Glexis A Rodriguez"
                  src="/profile.jpeg"
                  border={"4px"}
                  borderColor={"white"}
                  borderStyle={"solid"}
                />
                <Text textAlign={"center"}>Glexis Gomez</Text>
              </Box>
            </Box>
            <Container>{children}</Container>
          </Box>
        </Providers>
        <Suspense fallback={null}>
          <FacebookPixelEvents />
        </Suspense>
      </body>
    </html>
  );
}
